name: Rust
on:
  push:
  pull_request:
    branches: [ "develop" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/voldeno/blocks_check:latest
    steps:
    - uses: actions/checkout@v3
    - name: Check
      run: blocks_validator --funcs functions.txt --resources .
